name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant Execute Permission to Maven Wrapper
        run: chmod +x ./mvnw

      # Compile
      - name: Compile
        run: ./mvnw clean compile

      # Test Cases
      - name: Run Tests
        run: ./mvnw test


      # Build
      - name: Build Artifact
        run: ./mvnw clean install
