name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK and Maven
      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Projenize uygun JDK sürümünü belirtin
          distribution: 'temurin'
          cache: maven # Maven'ı yükler ve Maven cache'ini etkinleştirir

      # Compile
      - name: Compile
        run: mvn clean compile

      # Test Cases
      - name: Run Tests
        run: mvn test

      # Build
      - name: Build Artifact
        run: mvn clean install
