name: Create and publish a Docker image
on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  IMAGE_NAME: ersinsari/full-devsecops

jobs:
  build-scan-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build multi-architecture image locally
        run: |
            docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t docker.io/ersinsari/full-devsecops:latest \
            .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          github-pat: '${{ secrets.GITHUB }}'
          trivy-config: trivy.yaml

      - name: Debug SARIF File Path
        run: ls -l trivy-results.sarif

      - name: Upload Trivy SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Build multi-architecture image locally
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}